Ogre::HardwarePixelBuffer Class Reference - OGRE Documentation
Ogre::HardwarePixelBuffer Class Reference abstract
RenderSystem
Specialisation of HardwareBuffer for a pixel buffer.
#include <OgreHardwarePixelBuffer.h>
Public Types
enum LockOptions {
HBL_NORMAL, HBL_DISCARD, HBL_READ_ONLY, HBL_NO_OVERWRITE,
HBL_WRITE_ONLY
}
Locking options.
enum Usage {
HBU_STATIC = 1, HBU_DYNAMIC = 2, HBU_WRITE_ONLY = 4, HBU_DISCARDABLE = 8,
HBU_STATIC_WRITE_ONLY = 5, HBU_DYNAMIC_WRITE_ONLY = 6, HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = 14
}
Enums describing buffer usage; not mutually exclusive.
Public Member Functions
HardwarePixelBuffer (uint32 mWidth, uint32 mHeight, uint32 mDepth, PixelFormat mFormat, HardwareBuffer::Usage usage, bool useSystemMemory, bool useShadowBuffer)
Should be called by HardwareBufferManager.
~HardwarePixelBuffer ()
virtual void _updateFromShadow (void)
Updates the real buffer from the shadow buffer, if required.
virtual void blit (const HardwarePixelBufferSharedPtr &src, const Image::Box &srcBox, const Image::Box &dstBox)
Copies a box from another PixelBuffer to a region of the this PixelBuffer.
void blit (const HardwarePixelBufferSharedPtr &src)
Convenience function that blits the entire source pixel buffer to this buffer.
virtual void blitFromMemory (const PixelBox &src, const Image::Box &dstBox)=0
Copies a region from normal memory to a region of this pixelbuffer.
void blitFromMemory (const PixelBox &src)
Convenience function that blits a pixelbox from memory to the entire buffer.
virtual void blitToMemory (const Image::Box &srcBox, const PixelBox &dst)=0
Copies a region of this pixelbuffer to normal memory.
void blitToMemory (const PixelBox &dst)
Convenience function that blits this entire buffer to a pixelbox.
virtual void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
Copy data from another buffer into this one.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
const PixelBox & getCurrentLock ()
Get the current locked region.
uint32 getDepth () const
Gets the depth of this buffer.
PixelFormat getFormat () const
Gets the native pixel format of this buffer.
uint32 getHeight () const
Gets the height of this buffer.
virtual RenderTexture * getRenderTarget (size_t slice=0)
Get a render target for this PixelBuffer, or a slice of it.
size_t getSizeInBytes (void) const
Returns the size of this buffer in bytes.
Usage getUsage (void) const
Returns the Usage flags with which this buffer was created.
uint32 getWidth () const
Gets the width of this buffer.
bool hasShadowBuffer (void) const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked (void) const
Returns whether or not this buffer is currently locked.
bool isSystemMemory (void) const
Returns whether this buffer is held in system memory.
virtual const PixelBox & lock (const Image::Box &lockBox, LockOptions options)
Lock the buffer for (potentially) reading / writing.
virtual void * lock (size_t offset, size_t length, LockOptions options)
Lock the buffer for (potentially) reading / writing.
void * lock (LockOptions options)
Lock the entire buffer for (potentially) reading / writing.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
virtual void readData (size_t offset, size_t length, void *pDest)
Reads data from the buffer and places it in the memory pointed to by pDest.
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
virtual void unlock (void)
Releases the lock on this buffer.
virtual void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false)
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Protected Member Functions
virtual void _clearSliceRTT (size_t zoffset)
Notify TextureBuffer of destruction of render target.
virtual PixelBox lockImpl (const Image::Box lockBox, LockOptions options)=0
Internal implementation of lock(), must be overridden in subclasses.
virtual void * lockImpl (size_t offset, size_t length, LockOptions options)
Internal implementation of lock(), do not OVERRIDE or CALL this for HardwarePixelBuffer implementations, but override the previous method.
virtual void unlockImpl (void)=0
Internal implementation of unlock()
Protected Attributes
PixelBox mCurrentLock
Currently locked region (local coords)
uint32 mDepth
PixelFormat mFormat
Internal format.
uint32 mHeight
bool mIsLocked
Image::Box mLockedBox
The current locked box of this surface (entire surface coords)
size_t mLockSize
size_t mLockStart
size_t mRowPitch
Pitches (offsets between rows and slices)
HardwareBuffer * mShadowBuffer
bool mShadowUpdated
size_t mSizeInBytes
size_t mSlicePitch
bool mSuppressHardwareUpdate
bool mSystemMemory
Usage mUsage
bool mUseShadowBuffer
uint32 mWidth
Extents.
Friends
class RenderTexture
Detailed Description
Specialisation of HardwareBuffer for a pixel buffer.
The HardwarePixelbuffer abstracts an 1D, 2D or 3D quantity of pixels stored by the rendering API. The buffer can be located on the card or in main memory depending on its usage. One mipmap level of a texture is an example of a HardwarePixelBuffer.
Definition at line 53 of file OgreHardwarePixelBuffer.h.
Member Enumeration Documentation
enum Ogre::HardwareBuffer::LockOptions inherited
Locking options.
Enumerator
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
HBL_DISCARD
Discards the entire buffer while locking; this allows optimisation to be performed because synchronisation issues are relaxed.
Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_DISCARD, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
HBL_WRITE_ONLY
Lock the buffer for writing only.
Definition at line 121 of file OgreHardwareBuffer.h.
enum Ogre::HardwareBuffer::Usage inherited
Enums describing buffer usage; not mutually exclusive.
Enumerator
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE.
Definition at line 79 of file OgreHardwareBuffer.h.
Constructor & Destructor Documentation
Ogre::HardwarePixelBuffer::HardwarePixelBuffer (uint32 mWidth, uint32 mHeight, uint32 mDepth, PixelFormat mFormat, HardwareBuffer::Usage usage, bool useSystemMemory, bool useShadowBuffer)
Should be called by HardwareBufferManager.
Ogre::HardwarePixelBuffer::~HardwarePixelBuffer ()
Member Function Documentation
virtual void Ogre::HardwarePixelBuffer::_clearSliceRTT (size_t zoffset) protected virtual
Notify TextureBuffer of destruction of render target.
Called by RenderTexture when destroyed.
virtual void Ogre::HardwareBuffer::_updateFromShadow (void) virtual inherited
Updates the real buffer from the shadow buffer, if required.
Definition at line 305 of file OgreHardwareBuffer.h.
virtual void Ogre::HardwarePixelBuffer::blit (const HardwarePixelBufferSharedPtr & src, const Image::Box & srcBox, const Image::Box & dstBox) virtual
Copies a box from another PixelBuffer to a region of the this PixelBuffer.
Parameters
src Source pixel buffer
srcBox Image::Box describing the source region in src
dstBox Image::Box describing the destination region in this buffer
Remarks
The source and destination regions dimensions don't have to match, in which case scaling is done. This scaling is generally done using a bilinear filter in hardware, but it is faster to pass the source image in the right dimensions.
Note
Only call this function when both buffers are unlocked.
void Ogre::HardwarePixelBuffer::blit (const HardwarePixelBufferSharedPtr & src)
Convenience function that blits the entire source pixel buffer to this buffer.
If source and destination dimensions don't match, scaling is done.
Parameters
src PixelBox containing the source pixels and format in memory
Note
Only call this function when the buffer is unlocked.
virtual void Ogre::HardwarePixelBuffer::blitFromMemory (const PixelBox & src, const Image::Box & dstBox) pure virtual
Copies a region from normal memory to a region of this pixelbuffer.
The source image can be in any pixel format supported by OGRE, and in any size.
Parameters
src PixelBox containing the source pixels and format in memory
dstBox Image::Box describing the destination region in this buffer
Remarks
The source and destination regions dimensions don't have to match, in which case scaling is done. This scaling is generally done using a bilinear filter in hardware, but it is faster to pass the source image in the right dimensions.
Note
Only call this function when the buffer is unlocked.
void Ogre::HardwarePixelBuffer::blitFromMemory (const PixelBox & src)
Convenience function that blits a pixelbox from memory to the entire buffer.
The source image is scaled as needed.
Parameters
src PixelBox containing the source pixels and format in memory
Note
Only call this function when the buffer is unlocked.
Definition at line 149 of file OgreHardwarePixelBuffer.h.
virtual void Ogre::HardwarePixelBuffer::blitToMemory (const Image::Box & srcBox, const PixelBox & dst) pure virtual
Copies a region of this pixelbuffer to normal memory.
Parameters
srcBox Image::Box describing the source region of this buffer
dst PixelBox describing the destination pixels and format in memory
Remarks
The source and destination regions don't have to match, in which case scaling is done.
Note
Only call this function when the buffer is unlocked.
void Ogre::HardwarePixelBuffer::blitToMemory (const PixelBox & dst)
Convenience function that blits this entire buffer to a pixelbox.
The image is scaled as needed.
Parameters
dst PixelBox describing the destination pixels and format in memory
Note
Only call this function when the buffer is unlocked.
Definition at line 168 of file OgreHardwarePixelBuffer.h.
virtual void Ogre::HardwareBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) virtual inherited
Copy data from another buffer into this one.
Remarks
Note that the source buffer must not be created with the usage HBU_WRITE_ONLY otherwise this will fail.
Parameters
srcBuffer The buffer from which to read the copied data
srcOffset Offset in the source buffer at which to start reading
dstOffset Offset in the destination buffer to start writing
length Length of the data to copy, in bytes.
discardWholeBuffer If true, will discard the entire contents of this buffer before copying
Definition at line 284 of file OgreHardwareBuffer.h.
References Ogre::HardwareBuffer::lock(), and Ogre::HardwareBuffer::unlock().
virtual void Ogre::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) virtual inherited
Copy all data from another buffer into this one.
Remarks
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
Definition at line 298 of file OgreHardwareBuffer.h.
References Ogre::HardwareBuffer::getSizeInBytes().
const PixelBox& Ogre::HardwarePixelBuffer::getCurrentLock ()
Get the current locked region.
This is the same value as returned by lock(const Image::Box, LockOptions)
Returns
PixelBox containing the locked region
uint32 Ogre::HardwarePixelBuffer::getDepth () const
Gets the depth of this buffer.
Definition at line 187 of file OgreHardwarePixelBuffer.h.
PixelFormat Ogre::HardwarePixelBuffer::getFormat () const
Gets the native pixel format of this buffer.
Definition at line 189 of file OgreHardwarePixelBuffer.h.
uint32 Ogre::HardwarePixelBuffer::getHeight () const
Gets the height of this buffer.
Definition at line 185 of file OgreHardwarePixelBuffer.h.
virtual RenderTexture* Ogre::HardwarePixelBuffer::getRenderTarget (size_t slice = 0) virtual
Get a render target for this PixelBuffer, or a slice of it.
The texture this was acquired from must have TU_RENDERTARGET set, otherwise it is possible to render to it and this method will throw an ERR_RENDERSYSTEM exception.
Parameters
slice Which slice
Returns
A pointer to the render target. This pointer has the lifespan of this PixelBuffer.
size_t Ogre::HardwareBuffer::getSizeInBytes (void) const inherited
Returns the size of this buffer in bytes.
Definition at line 330 of file OgreHardwareBuffer.h.
Referenced by Ogre::HardwareBuffer::copyData().
Usage Ogre::HardwareBuffer::getUsage (void) const inherited
Returns the Usage flags with which this buffer was created.
Definition at line 332 of file OgreHardwareBuffer.h.
uint32 Ogre::HardwarePixelBuffer::getWidth () const
Gets the width of this buffer.
Definition at line 183 of file OgreHardwarePixelBuffer.h.
bool Ogre::HardwareBuffer::hasShadowBuffer (void) const inherited
Returns whether this buffer has a system memory shadow for quicker reading.
Definition at line 336 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::isLocked (void) const inherited
Returns whether or not this buffer is currently locked.
Definition at line 338 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::isSystemMemory (void) const inherited
Returns whether this buffer is held in system memory.
Definition at line 334 of file OgreHardwareBuffer.h.
virtual const PixelBox& Ogre::HardwarePixelBuffer::lock (const Image::Box & lockBox, LockOptions options) virtual
Lock the buffer for (potentially) reading / writing.
Parameters
lockBox Region of the buffer to lock
options Locking options
Returns
PixelBox containing the locked region, the pitches and the pixel format
virtual void* Ogre::HardwarePixelBuffer::lock (size_t offset, size_t length, LockOptions options) virtual
Lock the buffer for (potentially) reading / writing.
Parameters
offset The byte offset from the start of the buffer to lock
length The size of the area to lock, in bytes
options Locking options
Returns
Pointer to the locked memory
Reimplemented from Ogre::HardwareBuffer.
void* Ogre::HardwareBuffer::lock (LockOptions options) inherited
Lock the entire buffer for (potentially) reading / writing.
Parameters
options Locking options
Returns
Pointer to the locked memory
Definition at line 220 of file OgreHardwareBuffer.h.
virtual PixelBox Ogre::HardwarePixelBuffer::lockImpl (const Image::Box lockBox, LockOptions options) protected pure virtual
Internal implementation of lock(), must be overridden in subclasses.
virtual void* Ogre::HardwarePixelBuffer::lockImpl (size_t offset, size_t length, LockOptions options) protected virtual
Internal implementation of lock(), do not OVERRIDE or CALL this for HardwarePixelBuffer implementations, but override the previous method.
Implements Ogre::HardwareBuffer.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inherited
Definition at line 96 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inherited
Definition at line 102 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inherited
Definition at line 108 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inherited
Definition at line 113 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inherited
Definition at line 119 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inherited
operator new, with debug line info
Definition at line 68 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inherited
Definition at line 73 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inherited
placement operator new
Definition at line 79 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inherited
array operator new, with debug line info
Definition at line 86 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inherited
Definition at line 91 of file OgreMemoryAllocatedObject.h.
virtual void Ogre::HardwarePixelBuffer::readData (size_t offset, size_t length, void * pDest) virtual
Reads data from the buffer and places it in the memory pointed to by pDest.
Parameters
offset The byte offset from the start of the buffer to read
length The size of the area to read, in bytes
pDest The area of memory in which to place the data, must be large enough to accommodate the data!
Implements Ogre::HardwareBuffer.
void Ogre::HardwareBuffer::suppressHardwareUpdate (bool suppress) inherited
Pass true to suppress hardware upload of shadow buffer changes.
Definition at line 342 of file OgreHardwareBuffer.h.
virtual void Ogre::HardwareBuffer::unlock (void) virtual inherited
Releases the lock on this buffer.
Remarks
Locking and unlocking a buffer can, in some rare circumstances such as switching video modes whilst the buffer is locked, corrupt the contents of a buffer. This is pretty rare, but if it occurs, this method will throw an exception, meaning you must re-upload the data.
Note that using the 'read' and 'write' forms of updating the buffer does not suffer from this problem, so if you want to be 100% sure your data will not be lost, use the 'read' and 'write' forms instead.
Reimplemented in Ogre::DefaultHardwareCounterBuffer, Ogre::DefaultHardwareUniformBuffer, Ogre::DefaultHardwareIndexBuffer, and Ogre::DefaultHardwareVertexBuffer.
Definition at line 236 of file OgreHardwareBuffer.h.
Referenced by Ogre::HardwareBuffer::copyData().
virtual void Ogre::HardwareBuffer::unlockImpl (void) protected pure virtual inherited
Internal implementation of unlock()
Implemented in Ogre::DefaultHardwareCounterBuffer, Ogre::DefaultHardwareUniformBuffer, Ogre::DefaultHardwareIndexBuffer, and Ogre::DefaultHardwareVertexBuffer.
virtual void Ogre::HardwarePixelBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) virtual
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Parameters
offset The byte offset from the start of the buffer to start writing
length The size of the data to write to, in bytes
pSource The source of the data to be written
discardWholeBuffer If true, this allows the driver to discard the entire buffer when writing, such that DMA stalls can be avoided; use if you can.
Implements Ogre::HardwareBuffer.
Friends And Related Function Documentation
friend class RenderTexture friend
Definition at line 79 of file OgreHardwarePixelBuffer.h.
Member Data Documentation
PixelBox Ogre::HardwarePixelBuffer::mCurrentLock protected
Currently locked region (local coords)
Definition at line 63 of file OgreHardwarePixelBuffer.h.
uint32 Ogre::HardwarePixelBuffer::mDepth protected
Definition at line 57 of file OgreHardwarePixelBuffer.h.
PixelFormat Ogre::HardwarePixelBuffer::mFormat protected
Internal format.
Definition at line 61 of file OgreHardwarePixelBuffer.h.
uint32 Ogre::HardwarePixelBuffer::mHeight protected
Definition at line 57 of file OgreHardwarePixelBuffer.h.
bool Ogre::HardwareBuffer::mIsLocked protected inherited
Definition at line 145 of file OgreHardwareBuffer.h.
Image::Box Ogre::HardwarePixelBuffer::mLockedBox protected
The current locked box of this surface (entire surface coords)
Definition at line 65 of file OgreHardwarePixelBuffer.h.
size_t Ogre::HardwareBuffer::mLockSize protected inherited
Definition at line 147 of file OgreHardwareBuffer.h.
size_t Ogre::HardwareBuffer::mLockStart protected inherited
Definition at line 146 of file OgreHardwareBuffer.h.
size_t Ogre::HardwarePixelBuffer::mRowPitch protected
Pitches (offsets between rows and slices)
Definition at line 59 of file OgreHardwarePixelBuffer.h.
HardwareBuffer* Ogre::HardwareBuffer::mShadowBuffer protected inherited
Definition at line 150 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mShadowUpdated protected inherited
Definition at line 151 of file OgreHardwareBuffer.h.
size_t Ogre::HardwareBuffer::mSizeInBytes protected inherited
Definition at line 143 of file OgreHardwareBuffer.h.
size_t Ogre::HardwarePixelBuffer::mSlicePitch protected
Definition at line 59 of file OgreHardwarePixelBuffer.h.
bool Ogre::HardwareBuffer::mSuppressHardwareUpdate protected inherited
Definition at line 152 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mSystemMemory protected inherited
Definition at line 148 of file OgreHardwareBuffer.h.
Usage Ogre::HardwareBuffer::mUsage protected inherited
Definition at line 144 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mUseShadowBuffer protected inherited
Definition at line 149 of file OgreHardwareBuffer.h.
uint32 Ogre::HardwarePixelBuffer::mWidth protected
Extents.
Definition at line 57 of file OgreHardwarePixelBuffer.h.
The documentation for this class was generated from the following file:
OgreHardwarePixelBuffer.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Mon Nov 25 2013 22:28:00