Ogre::ColourFaderAffector2 Class Reference - OGRE Documentation
Ogre::ColourFaderAffector2 Class Reference
This plugin subclass of ParticleAffector allows you to alter the colour of particles.
#include <OgreColourFaderAffector2.h>
Classes
class CmdAlphaAdjust1
Command object for alpha adjust (see ParamCommand).
class CmdAlphaAdjust2
Command object for alpha adjust (see ParamCommand).
class CmdBlueAdjust1
Command object for blue adjust (see ParamCommand).
class CmdBlueAdjust2
Command object for blue adjust (see ParamCommand).
class CmdGreenAdjust1
Command object for green adjust (see ParamCommand).
class CmdGreenAdjust2
Command object for green adjust (see ParamCommand).
class CmdRedAdjust1
Command object for red adjust (see ParamCommand).
class CmdRedAdjust2
Command object for red adjust (see ParamCommand).
class CmdStateChange
Command object for alpha adjust (see ParamCommand).
Public Member Functions
ColourFaderAffector2 (ParticleSystem *psys)
Default constructor.
void _affectParticles (ParticleSystem *pSystem, Real timeElapsed)
See ParticleAffector.
virtual void _initParticle (Particle *pParticle)
Method called to allow the affector to initialize all newly created particles in the system.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
float getAlphaAdjust1 (void) const
Gets the alpha adjustment to be made per second to particles.
float getAlphaAdjust2 (void) const
float getBlueAdjust1 (void) const
Gets the blue adjustment to be made per second to particles.
float getBlueAdjust2 (void) const
float getGreenAdjust1 (void) const
Gets the green adjustment to be made per second to particles.
float getGreenAdjust2 (void) const
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
float getRedAdjust1 (void) const
Gets the red adjustment to be made per second to particles.
float getRedAdjust2 (void) const
Real getStateChange (void) const
const String & getType (void) const
Returns the name of the type of affector.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void setAdjust1 (float red, float green, float blue, float alpha=0.0)
Sets the colour adjustment to be made per second to particles.
void setAdjust2 (float red, float green, float blue, float alpha=0.0)
void setAlphaAdjust1 (float alpha)
Sets the alpha adjustment to be made per second to particles.
void setAlphaAdjust2 (float alpha)
void setBlueAdjust1 (float blue)
Sets the blue adjustment to be made per second to particles.
void setBlueAdjust2 (float blue)
void setGreenAdjust1 (float green)
Sets the green adjustment to be made per second to particles.
void setGreenAdjust2 (float green)
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
void setRedAdjust1 (float red)
Sets the red adjustment to be made per second to particles.
void setRedAdjust2 (float red)
void setStateChange (Real NewValue)
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre,
otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Static Public Attributes
static CmdAlphaAdjust1 msAlphaCmd1
static CmdAlphaAdjust2 msAlphaCmd2
static CmdBlueAdjust1 msBlueCmd1
static CmdBlueAdjust2 msBlueCmd2
static CmdGreenAdjust1 msGreenCmd1
static CmdGreenAdjust2 msGreenCmd2
static CmdRedAdjust1 msRedCmd1
static CmdRedAdjust2 msRedCmd2
static CmdStateChange msStateCmd
Protected Member Functions
void addBaseParameters (void)
Internal method for setting up the basic parameter definitions for a subclass.
void applyAdjustWithClamp (float *pComponent, float adjust)
Internal method for adjusting while clamping to [0,1].
bool createParamDictionary (const String &className)
Internal method for creating a parameter dictionary for the class, if it does not already exist.
Protected Attributes
float mAlphaAdj1
float mAlphaAdj2
float mBlueAdj1
float mBlueAdj2
float mGreenAdj1
float mGreenAdj2
ParticleSystem * mParent
float mRedAdj1
float mRedAdj2
String mType
Name of the type of affector, MUST be initialised by subclasses.
Real StateChangeVal
Detailed Description
This plugin subclass of ParticleAffector allows you to alter the colour of particles.
Remarks
This class supplies the ParticleAffector implementation required to modify the colour of particle in mid-flight.
Definition at line 43 of file OgreColourFaderAffector2.h.
Constructor & Destructor Documentation
Ogre::ColourFaderAffector2::ColourFaderAffector2 (ParticleSystem * psys)
Default constructor.
Member Function Documentation
void Ogre::ColourFaderAffector2::_affectParticles (ParticleSystem * pSystem, Real timeElapsed) virtual
See ParticleAffector.
Implements Ogre::ParticleAffector.
virtual void Ogre::ParticleAffector::_initParticle (Particle * pParticle) virtual inherited
Method called to allow the affector to initialize all newly created particles in the system.
Remarks
This is where the affector gets the chance to initialize it's effects to the particles of a system. The affector is expected to initialize some or all of the particles in the system passed to it, depending on the affector's approach.
Parameters
pParticle Pointer to a Particle to initialize.
Reimplemented in Ogre::RotationAffector, and Ogre::ColourImageAffector.
Definition at line 95 of file OgreParticleAffector.h.
void Ogre::ParticleAffector::addBaseParameters (void) protected inherited
Internal method for setting up the basic parameter definitions for a subclass.
Remarks
Because StringInterface holds a dictionary of parameters per class, subclasses need to call this to ask the base class to add it's parameters to their dictionary as well. Can't do this in the constructor because that runs in a non-virtual context.
The subclass must have called it's own createParamDictionary before calling this method.
Definition at line 78 of file OgreParticleAffector.h.
void Ogre::ColourFaderAffector2::applyAdjustWithClamp (float * pComponent, float adjust) protected
Internal method for adjusting while clamping to [0,1].
Definition at line 204 of file OgreColourFaderAffector2.h.
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre,
otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
Definition at line 303 of file OgreStringInterface.h.
References Ogre::ParamDictionary::mParamDefs, and Ogre::StringInterface::setParameter().
bool Ogre::StringInterface::createParamDictionary (const String & className) protected inherited
Internal method for creating a parameter dictionary for the class, if it does not already exist.
Remarks
This method will check to see if a parameter dictionary exist for this class yet, and if not will create one. NB you must supply the name of the class (RTTI is not used or performance).
Parameters
className the name of the class using the dictionary
Returns
true if a new dictionary was created, false if it was already there
Definition at line 186 of file OgreStringInterface.h.
References OGRE_LOCK_MUTEX.
float Ogre::ColourFaderAffector2::getAlphaAdjust1 (void) const
Gets the alpha adjustment to be made per second to particles.
float Ogre::ColourFaderAffector2::getAlphaAdjust2 (void) const
float Ogre::ColourFaderAffector2::getBlueAdjust1 (void) const
Gets the blue adjustment to be made per second to particles.
float Ogre::ColourFaderAffector2::getBlueAdjust2 (void) const
float Ogre::ColourFaderAffector2::getGreenAdjust1 (void) const
Gets the green adjustment to be made per second to particles.
float Ogre::ColourFaderAffector2::getGreenAdjust2 (void) const
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
Definition at line 219 of file OgreStringInterface.h.
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inherited
Definition at line 224 of file OgreStringInterface.h.
virtual String Ogre::StringInterface::getParameter (const String & name) const virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
Definition at line 272 of file OgreStringInterface.h.
References Ogre::ParamCommand::doGet(), and Ogre::ParamDictionary::getParamCommand().
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
float Ogre::ColourFaderAffector2::getRedAdjust1 (void) const
Gets the red adjustment to be made per second to particles.
float Ogre::ColourFaderAffector2::getRedAdjust2 (void) const
Real Ogre::ColourFaderAffector2::getStateChange (void) const
const String& Ogre::ParticleAffector::getType (void) const inherited
Returns the name of the type of affector.
Remarks
This property is useful for determining the type of affector procedurally so another can be created.
Definition at line 118 of file OgreParticleAffector.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inherited
Definition at line 96 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inherited
Definition at line 102 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inherited
Definition at line 108 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inherited
Definition at line 113 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inherited
Definition at line 119 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inherited
operator new, with debug line info
Definition at line 68 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inherited
Definition at line 73 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inherited
placement operator new
Definition at line 79 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inherited
array operator new, with debug line info
Definition at line 86 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inherited
Definition at line 91 of file OgreMemoryAllocatedObject.h.
void Ogre::ColourFaderAffector2::setAdjust1 (float red, float green, float blue, float alpha = 0.0)
Sets the colour adjustment to be made per second to particles.
Parameters
red,green,blue,alpha Sets the adjustment to be made to each of the colour components per second. These values will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
void Ogre::ColourFaderAffector2::setAdjust2 (float red, float green, float blue, float alpha = 0.0)
void Ogre::ColourFaderAffector2::setAlphaAdjust1 (float alpha)
Sets the alpha adjustment to be made per second to particles.
Parameters
alpha The adjustment to be made to the colour component per second. This value will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
void Ogre::ColourFaderAffector2::setAlphaAdjust2 (float alpha)
void Ogre::ColourFaderAffector2::setBlueAdjust1 (float blue)
Sets the blue adjustment to be made per second to particles.
Parameters
blue The adjustment to be made to the colour component per second. This value will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
void Ogre::ColourFaderAffector2::setBlueAdjust2 (float blue)
void Ogre::ColourFaderAffector2::setGreenAdjust1 (float green)
Sets the green adjustment to be made per second to particles.
Parameters
green The adjustment to be made to the colour component per second. This value will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
void Ogre::ColourFaderAffector2::setGreenAdjust2 (float green)
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
void Ogre::ColourFaderAffector2::setRedAdjust1 (float red)
Sets the red adjustment to be made per second to particles.
Parameters
red The adjustment to be made to the colour component per second. This value will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
void Ogre::ColourFaderAffector2::setRedAdjust2 (float red)
void Ogre::ColourFaderAffector2::setStateChange (Real NewValue)
Member Data Documentation
float Ogre::ColourFaderAffector2::mAlphaAdj1 protected
Definition at line 200 of file OgreColourFaderAffector2.h.
float Ogre::ColourFaderAffector2::mAlphaAdj2 protected
Definition at line 200 of file OgreColourFaderAffector2.h.
float Ogre::ColourFaderAffector2::mBlueAdj1 protected
Definition at line 199 of file OgreColourFaderAffector2.h.
float Ogre::ColourFaderAffector2::mBlueAdj2 protected
Definition at line 199 of file OgreColourFaderAffector2.h.
float Ogre::ColourFaderAffector2::mGreenAdj1 protected
Definition at line 198 of file OgreColourFaderAffector2.h.
float Ogre::ColourFaderAffector2::mGreenAdj2 protected
Definition at line 198 of file OgreColourFaderAffector2.h.
ParticleSystem* Ogre::ParticleAffector::mParent protected inherited
Definition at line 80 of file OgreParticleAffector.h.
float Ogre::ColourFaderAffector2::mRedAdj1 protected
Definition at line 197 of file OgreColourFaderAffector2.h.
float Ogre::ColourFaderAffector2::mRedAdj2 protected
Definition at line 197 of file OgreColourFaderAffector2.h.
CmdAlphaAdjust1 Ogre::ColourFaderAffector2::msAlphaCmd1 static
Definition at line 192 of file OgreColourFaderAffector2.h.
CmdAlphaAdjust2 Ogre::ColourFaderAffector2::msAlphaCmd2 static
Definition at line 193 of file OgreColourFaderAffector2.h.
CmdBlueAdjust1 Ogre::ColourFaderAffector2::msBlueCmd1 static
Definition at line 190 of file OgreColourFaderAffector2.h.
CmdBlueAdjust2 Ogre::ColourFaderAffector2::msBlueCmd2 static
Definition at line 191 of file OgreColourFaderAffector2.h.
CmdGreenAdjust1 Ogre::ColourFaderAffector2::msGreenCmd1 static
Definition at line 188 of file OgreColourFaderAffector2.h.
CmdGreenAdjust2 Ogre::ColourFaderAffector2::msGreenCmd2 static
Definition at line 189 of file OgreColourFaderAffector2.h.
CmdRedAdjust1 Ogre::ColourFaderAffector2::msRedCmd1 static
Definition at line 186 of file OgreColourFaderAffector2.h.
CmdRedAdjust2 Ogre::ColourFaderAffector2::msRedCmd2 static
Definition at line 187 of file OgreColourFaderAffector2.h.
CmdStateChange Ogre::ColourFaderAffector2::msStateCmd static
Definition at line 194 of file OgreColourFaderAffector2.h.
String Ogre::ParticleAffector::mType protected inherited
Name of the type of affector, MUST be initialised by subclasses.
Definition at line 68 of file OgreParticleAffector.h.
Real Ogre::ColourFaderAffector2::StateChangeVal protected
Definition at line 201 of file OgreColourFaderAffector2.h.
The documentation for this class was generated from the following file:
OgreColourFaderAffector2.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Mon Nov 25 2013 22:27:57