Ogre::DefaultHardwareCounterBuffer Class Reference - OGRE Documentation
Ogre::DefaultHardwareCounterBuffer Class Reference
RenderSystem
Specialisation of HardwareCounterBuffer for emulation.
#include <OgreDefaultHardwareBufferManager.h>
Public Types
enum LockOptions {
HBL_NORMAL, HBL_DISCARD, HBL_READ_ONLY, HBL_NO_OVERWRITE,
HBL_WRITE_ONLY
}
Locking options.
enum Usage {
HBU_STATIC = 1, HBU_DYNAMIC = 2, HBU_WRITE_ONLY = 4, HBU_DISCARDABLE = 8,
HBU_STATIC_WRITE_ONLY = 5, HBU_DYNAMIC_WRITE_ONLY = 6, HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = 14
}
Enums describing buffer usage; not mutually exclusive.
Public Member Functions
DefaultHardwareCounterBuffer (HardwareBufferManagerBase *mgr, size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer=false, const String &name="")
~DefaultHardwareCounterBuffer ()
virtual void _updateFromShadow (void)
Updates the real buffer from the shadow buffer, if required.
virtual void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
Copy data from another buffer into this one.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
HardwareBufferManagerBase * getManager () const
Return the manager of this buffer, if any.
const String & getName () const
size_t getSizeInBytes (void) const
Returns the size of this buffer in bytes.
Usage getUsage (void) const
Returns the Usage flags with which this buffer was created.
bool hasShadowBuffer (void) const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked (void) const
Returns whether or not this buffer is currently locked.
bool isSystemMemory (void) const
Returns whether this buffer is held in system memory.
void * lock (size_t offset, size_t length, LockOptions options)
Override HardwareBuffer to turn off all shadowing.
void * lock (LockOptions options)
Lock the entire buffer for (potentially) reading / writing.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void readData (size_t offset, size_t length, void *pDest)
See HardwareBuffer.
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
void unlock (void)
Override HardwareBuffer to turn off all shadowing.
void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false)
See HardwareBuffer.
Protected Member Functions
void * lockImpl (size_t offset, size_t length, LockOptions options)
See HardwareBuffer.
void unlockImpl (void)
See HardwareBuffer.
Protected Attributes
unsigned char * mData
bool mIsLocked
size_t mLockSize
size_t mLockStart
HardwareBufferManagerBase * mMgr
String mName
HardwareBuffer * mShadowBuffer
bool mShadowUpdated
size_t mSizeInBytes
bool mSuppressHardwareUpdate
bool mSystemMemory
Usage mUsage
bool mUseShadowBuffer
Detailed Description
Specialisation of HardwareCounterBuffer for emulation.
Definition at line 125 of file OgreDefaultHardwareBufferManager.h.
Member Enumeration Documentation
enum Ogre::HardwareBuffer::LockOptions inherited
Locking options.
Enumerator
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
HBL_DISCARD
Discards the entire buffer while locking; this allows optimisation to be performed because synchronisation issues are relaxed.
Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_DISCARD, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
HBL_WRITE_ONLY
Lock the buffer for writing only.
Definition at line 121 of file OgreHardwareBuffer.h.
enum Ogre::HardwareBuffer::Usage inherited
Enums describing buffer usage; not mutually exclusive.
Enumerator
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE.
Definition at line 79 of file OgreHardwareBuffer.h.
Constructor & Destructor Documentation
Ogre::DefaultHardwareCounterBuffer::DefaultHardwareCounterBuffer (HardwareBufferManagerBase * mgr, size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer = false, const String & name = "")
Ogre::DefaultHardwareCounterBuffer::~DefaultHardwareCounterBuffer ()
Member Function Documentation
virtual void Ogre::HardwareBuffer::_updateFromShadow (void) virtual inherited
Updates the real buffer from the shadow buffer, if required.
Definition at line 305 of file OgreHardwareBuffer.h.
virtual void Ogre::HardwareBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) virtual inherited
Copy data from another buffer into this one.
Remarks
Note that the source buffer must not be created with the usage HBU_WRITE_ONLY otherwise this will fail.
Parameters
srcBuffer The buffer from which to read the copied data
srcOffset Offset in the source buffer at which to start reading
dstOffset Offset in the destination buffer to start writing
length Length of the data to copy, in bytes.
discardWholeBuffer If true, will discard the entire contents of this buffer before copying
Definition at line 284 of file OgreHardwareBuffer.h.
References Ogre::HardwareBuffer::lock(), and Ogre::HardwareBuffer::unlock().
virtual void Ogre::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) virtual inherited
Copy all data from another buffer into this one.
Remarks
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
Definition at line 298 of file OgreHardwareBuffer.h.
References Ogre::HardwareBuffer::getSizeInBytes().
size_t Ogre::HardwareBuffer::getSizeInBytes (void) const inherited
Returns the size of this buffer in bytes.
Definition at line 330 of file OgreHardwareBuffer.h.
Referenced by Ogre::HardwareBuffer::copyData().
Usage Ogre::HardwareBuffer::getUsage (void) const inherited
Returns the Usage flags with which this buffer was created.
Definition at line 332 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::hasShadowBuffer (void) const inherited
Returns whether this buffer has a system memory shadow for quicker reading.
Definition at line 336 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::isLocked (void) const inherited
Returns whether or not this buffer is currently locked.
Definition at line 338 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::isSystemMemory (void) const inherited
Returns whether this buffer is held in system memory.
Definition at line 334 of file OgreHardwareBuffer.h.
void* Ogre::DefaultHardwareCounterBuffer::lock (size_t offset, size_t length, LockOptions options) virtual
Override HardwareBuffer to turn off all shadowing.
Reimplemented from Ogre::HardwareBuffer.
void* Ogre::HardwareBuffer::lock (LockOptions options) inherited
Lock the entire buffer for (potentially) reading / writing.
Parameters
options Locking options
Returns
Pointer to the locked memory
Definition at line 220 of file OgreHardwareBuffer.h.
void* Ogre::DefaultHardwareCounterBuffer::lockImpl (size_t offset, size_t length, LockOptions options) protected virtual
See HardwareBuffer.
Implements Ogre::HardwareBuffer.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inherited
Definition at line 96 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inherited
Definition at line 102 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inherited
Definition at line 108 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inherited
Definition at line 113 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inherited
Definition at line 119 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inherited
operator new, with debug line info
Definition at line 68 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inherited
Definition at line 73 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inherited
placement operator new
Definition at line 79 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inherited
array operator new, with debug line info
Definition at line 86 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inherited
Definition at line 91 of file OgreMemoryAllocatedObject.h.
void Ogre::DefaultHardwareCounterBuffer::readData (size_t offset, size_t length, void * pDest) virtual
See HardwareBuffer.
Implements Ogre::HardwareBuffer.
void Ogre::HardwareBuffer::suppressHardwareUpdate (bool suppress) inherited
Pass true to suppress hardware upload of shadow buffer changes.
Definition at line 342 of file OgreHardwareBuffer.h.
void Ogre::DefaultHardwareCounterBuffer::unlock (void) virtual
Override HardwareBuffer to turn off all shadowing.
Reimplemented from Ogre::HardwareBuffer.
void Ogre::DefaultHardwareCounterBuffer::unlockImpl (void) protected virtual
See HardwareBuffer.
Implements Ogre::HardwareBuffer.
void Ogre::DefaultHardwareCounterBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) virtual
See HardwareBuffer.
Implements Ogre::HardwareBuffer.
Member Data Documentation
unsigned char* Ogre::DefaultHardwareCounterBuffer::mData protected
Definition at line 128 of file OgreDefaultHardwareBufferManager.h.
bool Ogre::HardwareBuffer::mIsLocked protected inherited
Definition at line 145 of file OgreHardwareBuffer.h.
size_t Ogre::HardwareBuffer::mLockSize protected inherited
Definition at line 147 of file OgreHardwareBuffer.h.
size_t Ogre::HardwareBuffer::mLockStart protected inherited
Definition at line 146 of file OgreHardwareBuffer.h.
HardwareBuffer* Ogre::HardwareBuffer::mShadowBuffer protected inherited
Definition at line 150 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mShadowUpdated protected inherited
Definition at line 151 of file OgreHardwareBuffer.h.
size_t Ogre::HardwareBuffer::mSizeInBytes protected inherited
Definition at line 143 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mSuppressHardwareUpdate protected inherited
Definition at line 152 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mSystemMemory protected inherited
Definition at line 148 of file OgreHardwareBuffer.h.
Usage Ogre::HardwareBuffer::mUsage protected inherited
Definition at line 144 of file OgreHardwareBuffer.h.
bool Ogre::HardwareBuffer::mUseShadowBuffer protected inherited
Definition at line 149 of file OgreHardwareBuffer.h.
The documentation for this class was generated from the following file:
OgreDefaultHardwareBufferManager.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Mon Nov 25 2013 22:27:58