Ogre::APKFileSystemArchiveFactory Class Reference - OGRE Documentation
Ogre::APKFileSystemArchiveFactory Class Reference
#include <OgreAPKFileSystemArchive.h>
Public Member Functions
APKFileSystemArchiveFactory (AAssetManager *assetMgr)
virtual ~APKFileSystemArchiveFactory ()
virtual Archive * createInstance (const String &name)
Creates a new object.
Archive * createInstance (const String &name, bool readOnly)
Creates a new object.
void destroyInstance (Archive *arch)
Destroys an object which was created by this factory.
const String & getType (void) const
Returns the factory type.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
Private Attributes
AAssetManager * mAssetMgr
Detailed Description
Definition at line 83 of file OgreAPKFileSystemArchive.h.
Constructor & Destructor Documentation
Ogre::APKFileSystemArchiveFactory::APKFileSystemArchiveFactory (AAssetManager * assetMgr)
Definition at line 86 of file OgreAPKFileSystemArchive.h.
virtual Ogre::APKFileSystemArchiveFactory::~APKFileSystemArchiveFactory () virtual
Definition at line 87 of file OgreAPKFileSystemArchive.h.
Member Function Documentation
virtual Archive* Ogre::ArchiveFactory::createInstance (const String & name) virtual inherited
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Implements Ogre::FactoryObj< Archive >.
Definition at line 71 of file OgreArchiveFactory.h.
References Ogre::ArchiveFactory::createInstance().
Referenced by Ogre::ArchiveFactory::createInstance().
Archive* Ogre::APKFileSystemArchiveFactory::createInstance (const String & name, bool readOnly) virtual
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Implements Ogre::ArchiveFactory.
Definition at line 91 of file OgreAPKFileSystemArchive.h.
References getType(), mAssetMgr, and OGRE_NEW.
void Ogre::APKFileSystemArchiveFactory::destroyInstance (Archive * arch) virtual
Destroys an object which was created by this factory.
Parameters
ptr Pointer to the object to destroy
Implements Ogre::FactoryObj< Archive >.
Definition at line 96 of file OgreAPKFileSystemArchive.h.
References OGRE_DELETE.
const String& Ogre::APKFileSystemArchiveFactory::getType (void) const virtual
Returns the factory type.
Returns
The factory type.
Implements Ogre::FactoryObj< Archive >.
Referenced by createInstance().
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inherited
Definition at line 96 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inherited
Definition at line 102 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inherited
Definition at line 108 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inherited
Definition at line 113 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inherited
Definition at line 119 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inherited
operator new, with debug line info
Definition at line 68 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inherited
Definition at line 73 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inherited
placement operator new
Definition at line 79 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inherited
array operator new, with debug line info
Definition at line 86 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inherited
Definition at line 91 of file OgreMemoryAllocatedObject.h.
Member Data Documentation
AAssetManager* Ogre::APKFileSystemArchiveFactory::mAssetMgr private
Definition at line 98 of file OgreAPKFileSystemArchive.h.
Referenced by createInstance().
The documentation for this class was generated from the following file:
OgreAPKFileSystemArchive.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Mon Nov 25 2013 22:27:55