Ogre::APKZipArchiveFactory Class Reference - OGRE Documentation
Ogre::APKZipArchiveFactory Class Reference
#include <OgreAPKZipArchive.h>
Public Types
typedef bool(* DecryptEmbeddedZipFileFunc)(size_t pos, void *buf, size_t len)
a function type to decrypt embedded zip file
Public Member Functions
APKZipArchiveFactory (AAssetManager *assetMgr)
virtual ~APKZipArchiveFactory ()
Archive * createInstance (const String &name, bool readOnly)
Creates a new object.
virtual Archive * createInstance (const String &name)
Creates a new object.
void destroyInstance (Archive *ptr)
Destroys an object which was created by this factory.
const String & getType (void) const
Returns the factory type.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
Static Public Member Functions
static void addEmbbeddedFile (const String &name, const uint8 *fileData, size_t fileSize, DecryptEmbeddedZipFileFunc decryptFunc)
Add an embedded file to the embedded file list.
static void removeEmbbeddedFile (const String &name)
Remove an embedded file to the embedded file list.
Protected Attributes
AAssetManager * mAssetMgr
Static Protected Attributes
static zzip_plugin_io_handlers * mPluginIo
A static pointer to file io alternative implementation for the embedded files.
Detailed Description
Definition at line 38 of file OgreAPKZipArchive.h.
Member Typedef Documentation
typedef bool(* Ogre::EmbeddedZipArchiveFactory::DecryptEmbeddedZipFileFunc)(size_t pos, void *buf, size_t len) inherited
a function type to decrypt embedded zip file
Parameters
pos pos in file
buf current buffer to decrypt
len - length of buffer
Returns
success
Definition at line 156 of file OgreZip.h.
Constructor & Destructor Documentation
Ogre::APKZipArchiveFactory::APKZipArchiveFactory (AAssetManager * assetMgr)
Definition at line 43 of file OgreAPKZipArchive.h.
virtual Ogre::APKZipArchiveFactory::~APKZipArchiveFactory () virtual
Definition at line 44 of file OgreAPKZipArchive.h.
Member Function Documentation
static void Ogre::EmbeddedZipArchiveFactory::addEmbbeddedFile (const String & name, const uint8 * fileData, size_t fileSize, DecryptEmbeddedZipFileFunc decryptFunc) static inherited
Add an embedded file to the embedded file list.
Referenced by createInstance().
Archive* Ogre::APKZipArchiveFactory::createInstance (const String & name, bool readOnly) virtual
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Implements Ogre::ArchiveFactory.
Definition at line 50 of file OgreAPKZipArchive.h.
References Ogre::EmbeddedZipArchiveFactory::addEmbbeddedFile(), mAssetMgr, Ogre::EmbeddedZipArchiveFactory::mPluginIo, and OGRE_NEW.
virtual Archive* Ogre::ArchiveFactory::createInstance (const String & name) virtual inherited
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Implements Ogre::FactoryObj< Archive >.
Definition at line 71 of file OgreArchiveFactory.h.
References Ogre::ArchiveFactory::createInstance().
Referenced by Ogre::ArchiveFactory::createInstance().
void Ogre::ZipArchiveFactory::destroyInstance (Archive * ptr) virtual inherited
Destroys an object which was created by this factory.
Parameters
ptr Pointer to the object to destroy
Implements Ogre::FactoryObj< Archive >.
Definition at line 129 of file OgreZip.h.
References OGRE_DELETE.
const String& Ogre::APKZipArchiveFactory::getType (void) const virtual
Returns the factory type.
Returns
The factory type.
Implements Ogre::FactoryObj< Archive >.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inherited
Definition at line 96 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inherited
Definition at line 102 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inherited
Definition at line 108 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inherited
Definition at line 113 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inherited
Definition at line 119 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inherited
operator new, with debug line info
Definition at line 68 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inherited
Definition at line 73 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inherited
placement operator new
Definition at line 79 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inherited
array operator new, with debug line info
Definition at line 86 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inherited
Definition at line 91 of file OgreMemoryAllocatedObject.h.
static void Ogre::EmbeddedZipArchiveFactory::removeEmbbeddedFile (const String & name) static inherited
Remove an embedded file to the embedded file list.
Member Data Documentation
AAssetManager* Ogre::APKZipArchiveFactory::mAssetMgr protected
Definition at line 41 of file OgreAPKZipArchive.h.
Referenced by createInstance().
zzip_plugin_io_handlers* Ogre::EmbeddedZipArchiveFactory::mPluginIo static protected inherited
A static pointer to file io alternative implementation for the embedded files.
Definition at line 137 of file OgreZip.h.
Referenced by createInstance().
The documentation for this class was generated from the following file:
OgreAPKZipArchive.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Mon Nov 25 2013 22:27:55