Ogre::EmbeddedZipArchiveFactory Class Reference - OGRE Documentation
Ogre::EmbeddedZipArchiveFactory Class Reference
Resources
Specialisation of ZipArchiveFactory for embedded Zip files.
#include <OgreZip.h>
Public Types
typedef bool(* DecryptEmbeddedZipFileFunc)(size_t pos, void *buf, size_t len)
a function type to decrypt embedded zip file
Public Member Functions
EmbeddedZipArchiveFactory ()
virtual ~EmbeddedZipArchiveFactory ()
virtual Archive * createInstance (const String &name)
Creates a new object.
Archive * createInstance (const String &name, bool readOnly)
Creates a new object.
void destroyInstance (Archive *ptr)
Destroys an object which was created by this factory.
const String & getType (void) const
Returns the factory type.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
Static Public Member Functions
static void addEmbbeddedFile (const String &name, const uint8 *fileData, size_t fileSize, DecryptEmbeddedZipFileFunc decryptFunc)
Add an embedded file to the embedded file list.
static void removeEmbbeddedFile (const String &name)
Remove an embedded file to the embedded file list.
Static Protected Attributes
static zzip_plugin_io_handlers * mPluginIo
A static pointer to file io alternative implementation for the embedded files.
Detailed Description
Specialisation of ZipArchiveFactory for embedded Zip files.
Definition at line 133 of file OgreZip.h.
Member Typedef Documentation
typedef bool(* Ogre::EmbeddedZipArchiveFactory::DecryptEmbeddedZipFileFunc)(size_t pos, void *buf, size_t len)
a function type to decrypt embedded zip file
Parameters
pos pos in file
buf current buffer to decrypt
len - length of buffer
Returns
success
Definition at line 156 of file OgreZip.h.
Constructor & Destructor Documentation
Ogre::EmbeddedZipArchiveFactory::EmbeddedZipArchiveFactory ()
virtual Ogre::EmbeddedZipArchiveFactory::~EmbeddedZipArchiveFactory () virtual
Member Function Documentation
static void Ogre::EmbeddedZipArchiveFactory::addEmbbeddedFile (const String & name, const uint8 * fileData, size_t fileSize, DecryptEmbeddedZipFileFunc decryptFunc) static
Add an embedded file to the embedded file list.
Referenced by Ogre::APKZipArchiveFactory::createInstance().
virtual Archive* Ogre::ArchiveFactory::createInstance (const String & name) virtual inherited
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Implements Ogre::FactoryObj< Archive >.
Definition at line 71 of file OgreArchiveFactory.h.
References Ogre::ArchiveFactory::createInstance().
Referenced by Ogre::ArchiveFactory::createInstance().
Archive* Ogre::EmbeddedZipArchiveFactory::createInstance (const String & name, bool readOnly) virtual
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Reimplemented from Ogre::ZipArchiveFactory.
Definition at line 144 of file OgreZip.h.
References OGRE_NEW.
void Ogre::ZipArchiveFactory::destroyInstance (Archive * ptr) virtual inherited
Destroys an object which was created by this factory.
Parameters
ptr Pointer to the object to destroy
Implements Ogre::FactoryObj< Archive >.
Definition at line 129 of file OgreZip.h.
References OGRE_DELETE.
const String& Ogre::EmbeddedZipArchiveFactory::getType (void) const virtual
Returns the factory type.
Returns
The factory type.
Reimplemented from Ogre::ZipArchiveFactory.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inherited
Definition at line 96 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inherited
Definition at line 102 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inherited
Definition at line 108 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inherited
Definition at line 113 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inherited
Definition at line 119 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inherited
operator new, with debug line info
Definition at line 68 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inherited
Definition at line 73 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inherited
placement operator new
Definition at line 79 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inherited
array operator new, with debug line info
Definition at line 86 of file OgreMemoryAllocatedObject.h.
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inherited
Definition at line 91 of file OgreMemoryAllocatedObject.h.
static void Ogre::EmbeddedZipArchiveFactory::removeEmbbeddedFile (const String & name) static
Remove an embedded file to the embedded file list.
Member Data Documentation
zzip_plugin_io_handlers* Ogre::EmbeddedZipArchiveFactory::mPluginIo static protected
A static pointer to file io alternative implementation for the embedded files.
Definition at line 137 of file OgreZip.h.
Referenced by Ogre::APKZipArchiveFactory::createInstance().
The documentation for this class was generated from the following file:
OgreZip.h
Copyright © 2012 Torus Knot Software Ltd
This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
Last modified Mon Nov 25 2013 22:27:59